### ISSUE TITLE
Google Code shutting down: More organization needed

### ISSUE THREAD

**Issue by Narann** [mupen64plus/mupen64plus-core#102]
Hi all. As [you maybe know](http://google-opensource.blogspot.ca/2015/03/farewell-to-google-code.html), Google Code will be shutdown. Roughly:

* March 12, 2015 - New project creation disabled.
* August 24, 2015 - The site goes read-only. You can still checkout/view project source, issues, and wikis.
* January 25, 2016 - The project hosting service is closed. You will be able to download a tarball of project source, issues, and wikis. These tarballs will be available throughout the rest of 2016.

Technically, we have until August 24 to find where users could help each others. For now, a lot of help is provided under the google code [issue page](https://code.google.com/p/mupen64plus/issues/list)

I think it's important to keep github for dev related discussions, but we need to find a place for mupen64plus users to communicate, help each other, share, have fun, etc. :)

[mupen64plus.github.io](https://github.com/mupen64plus/mupen64plus.github.io) would be an interesting place to have a forum. But we definitely need a web dev for this.

But more important: Do we want this? I mean: Do we want mupen64plus to be more than an emulator? With a community of users/players/etc... Or do we want to let this to downstream projects?

IMHO, this is what make the difference between living projects or dying ones. Living projects can gather new contributors easily, have better/faster feedback, making work motivating. I was a mupen64plus user before jump into the code. You don't simply jump on the first ~dead~ project you found and if we don't fight a little, mupen64plus will look dead from the exterior.

I would also love to gather downstream projects into this forum, making a common place for devs to communicate with users. :)

@richard42 @bsmiles32 @gen2brain @Nebuleon @littleguy77 @twinaphex @cxd4 @conchurnavid and certainly others (don't hesitate to add them).

**Comment by wareya** [comment]
>But more important: Do we want this? I mean: Do we want mupen64plus to be more than an emulator? With a community of users/players/etc... Or do we want to let this to downstream projects?

Uuuuggghhh. Leaving everything to downstream projects is a Great way to get segregate the upstream community, especially once you count downstream projects that don't make any changes to the core.

Google Code was always a pretty freaking bad "community", we're already doing better dev-wise over here, and it's not like anyone who wanted to play through OoT for the second time ever went to Google Code and found a friendly community along the lines of PJ64's forums.

"Bringing back" the emutalk forum is always an option, but it's a severely unappealing forum to casual users. It looks extremely dead. At the time of writing this post, it simultaneously has 78k registered members and yet has had a small handful of posts in the past few days. When someone who's used to forums looks at that, they'll think "Oh, a dead community that they're trying to keep alive" or "I bet something dramatic happened to them, why aren't they posting?" (when really it mostly plays the role of an archive these days).

But, at the same time, if I take a step back and look at a couple different vague kinds of forum, I can see that, usually, one of the following happens:

* Someone's personal forum becomes a general forum for a community of people that arrive pretty much only because there are so many smart people that actually actively post there
* Popular emulator forums take over the entire discussion of the console they're emulating
* Forum dies due to severe drama and exodus of its members
* Forum "dies" spontaneously due to REALLY bad drama but keeps a close knit community of members that makes new members run far away fast
* Forum slowly dies due to one minor conflict after the other and then gets taken down because "why host it"
* Forum slowly dies because forums which are better-organized with better forum software and a better UX show up with active users
* Indie game forums live, prosper, and die in a span of about eight years
* Forums which never gain any popularity due to basically being the admin's blog and a few people asking them questions about what they're working on

So the only way I can see a M64P forum actually being used is if it works as a M64P service forum, the devs use it to keep track of some things (instead of github exclusively), and let other kinds of "off topic" conversation go on.

**Comment by conchurnavid** [comment]
How do you want to use https://github.com/mupen64plus/mupen64plus.github.io as a forum? It is not like you can put a phpbb in their. It is mainly for static sites which you can update through git.

**Comment by conchurnavid** [comment]
I am currently trying to save the old issues in a separate github repo which then can be also used to provide the downloads. But takes ages at the moment to run the google importer. Maybe at the end of the weekend it will have finished the import

**Comment by Narann** [comment]
@wareya Thanks!

@conchurnavid You are right, mupen64plus.github.io doesn't seems to really support dynamic forums. And thanks for trying to backup user's issues.

**Comment by conchurnavid** [comment]
I have now imported the issues, downloads and old source. Can be found at https://github.com/conchurnavid/mupen64plus

To which administrator of the mupen64plus organization should i transfer it? I cannot directly transfer it to the mupen64plus organization for some reason and instead the owner/administrator has to do it after he got the repository from me.

**Comment by bsmiles32** [comment]
@conchurnavid thanks for the backup !

Regarding the "community" forum, I think emutalk is still our best bet for now as it requires no additional work. The low number of messages is mostly because we haven't released anything new to the public in 2 years (+ plus other popular emu have moved to their respective forums [pj64,cen64]). If we release stuff more frequently I have no doubt that users will come there. Plus it would allow to separate user support (emutalk) from dev discussions (on github).

Also, with this migration of bugs, it would be a good time to go through every bug and re-evaluate them in order to close those that are fixed, reformulate those that are badly worded (user perspective, not dev perspective) before importing them on github. Doing that before the next release could help in avoiding embarrassing bugs that we might have forgotten.

Also question : is the googlegroup affected by this ? I don't think so, but just asking to be sure as there are some still useful discussion there.

**Comment by conchurnavid** [comment]
Why doing a reimport again? I spend 3 days kicking this importer tool to end up with this repo. Why now modifying the google code stuff to do everything again?

And the google group is not part of google code. But maybe we should decide which should be promoted on the next project page. Either google groups or emutalk. Splitting it over two forums with the same target audience sounds counter productive.

**Comment by bsmiles32** [comment]
@conchurnavid : No need to reimport everything again. We can work from your imported backup. It is just that there are quite a few bugs that are not relevant anymore. Anyway, we can do that at a later time depending on the time and resources available.

**Comment by Papermanzero** [comment]
It's just an idea and hint:
If you are searching for a bug tracker, a community and a documentation website, you can also use Atlassians open source support.
https://www.atlassian.com/opensource/overview

You can apply for Jira (Bug Tracking), Confluence (wiki and community) and Bitbucket (source code, daily builds -> which is already in use). The benefit is that you can interact with all tools (jira, confluence, bitbucket and github)
https://confluence.atlassian.com/display/BITBUCKET/Linking+Bitbucket+and+GitHub+accounts+to+JIRA

Alternatively you can use github as the "main portal" for issues and discussions.

**Comment by conchurnavid** [comment]
Looks like a more confusing version of redmine or trac after they fusioned with bitbucket. So maybe they are more for developers and not for end users, right?

**Comment by Papermanzero** [comment]
It's for different kind of users. The solution is very flexible. It depends how you setup Jira.
You can create jira projects for end users, developers, testers who can all enter bugs. But you can create certain workflows to assign the issues to developers, system components, testers etc. or create custom bug states (e.g. more Information needed, Verification of bug)
It's also used for feature requests, task management and so on.
All in all it's very powerful.
Youtube Video about Jira:
https://www.youtube.com/watch?v=xrCJv0fTyR8

Example of an Open Source Jira Project with links to GitHub:
https://hibernate.atlassian.net/secure/Dashboard.jspa

However and this is the most important point from my experience, you really have to know how to setup an intention/project. The correction afterwards is possible, but sometimes very time consuming.

**Comment by richard42** [comment]
Thanks to everyone here who has given their ideas and opinions for a way forward without Google Code.  There are definitely a lot of possibilities.  Unfortunately no easy ones though :)

My primary qualification for a successor to the Google Code site is something that can allow us to replicate the resources which we were previously hosting there, while taking a minimum of administrative effort.  Hopefully Google Groups will stick around for a few more years, so we will still have the mailing list.  We never hosted a forum on the Google Code site, so I don't really care about moving to a site which hosts a forum.  I always considered emutalk to be our 'home' forum, even though it has been a bit of a ghost town for the last couple of years.

In particular, the features which I am interested in for our GC replacement are:

1. Nice looking front page which can be a landing page for new users, to give general features, news, links to more in-depth informations, pictures, etc (same as current GC front page)
2. Download hosting for the release bundles.  It really sucks that github removed this feature
3. User-level wiki pages
4. User-focused issue tracker

SourceForge has been around forever, but I don't recall seeing very many project home pages that actually looked nice there.

I have my own domain (fascinationsoftware.com) and shared hosting service through HostGator.  I think the bandwidth of this shared hosting package is not very high though.  I also bought the mupen64plus.org domain.  Does it seem reasonable to just set up a shared hosting account somewhere and roll all of the services on our own?  I've set up MediaWiki a few times; that's no big deal.  Bugzilla is easy enough to set up too.  Migration could be a pain.  It would be easy to slap up some old school HTML for the front page, or use some CMS.

Any other ideas for free hosts which offer the services that I mentioned above?

**Comment by conchurnavid** [comment]
> In particular, the features which I am interested in for our GC replacement are:
> 
> 1. Nice looking front page which can be a landing page for new users, to give general features, news, links to more in-depth informations, pictures, etc (same as current GC front page)

I personally don't like the current page. It is just overloaded. But it is gone anyway in a few months

https://conchurnavid.github.io/

> 2. Download hosting for the release bundles. It really sucks that github removed this feature

https://github.com/conchurnavid/mupen64plus/releases/tag/2.0

> 3. User-level wiki pages

https://github.com/conchurnavid/mupen64plus/wiki/KeyboardSetup

> 4. User-focused issue tracker

https://github.com/conchurnavid/mupen64plus/issues

**Comment by bsmiles32** [comment]
@conchurnavid : I  really like what you've done here ! Website is nice and clean.

**Comment by richard42** [comment]
That's great, I like what you've done here too.  Was this all done primarily
with the Google migration tool, or did you have to do a lot of custom fiddling
as well?

**Comment by conchurnavid** [comment]
Issues came from the google exporter and the rest was mostly manual fiddling.

And there is still a lot to do. For example it would have to be discussed what is in the user wiki and what is in the documentation part of the website.

**Comment by richard42** [comment]
Alright, the migration is done.  Thanks to all of you for suggestions and help.

**Comment by sgorman** [comment]
Nice website Richard.

**Comment by Narann** [comment]
Thanks Richard!

For info, web site is here: http://mupen64plus.org/ (favicon would be nice. :D )

Should I remove the mupen64plus.github.io repo (as it's now pointless)?

**Comment by richard42** [comment]
yeah, I think we should delete the mupen64plus.github.io repository.

**Comment by Narann** [comment]
Done!

Great idea to have mupen64plus-user-issues! ;)
