### ISSUE TITLE
PIF rewrite broke loading save states at startup

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#405]
si_end_of_dma_event with a flags of 1 only happens at game startup. So if you are loading a save state at startup, a flags value of 1 never happens.

If you re-start the game and then load a save state, it works ok.

**Comment by loganmc10** [comment]
Thanks for tracking this down, I can reproduce this in Linux. When you say "flags value of 1" what do you mean exactly?

**Comment by loganmc10** [comment]
And yes, I bisected it to this commit: 752a7354b2b8a71029bc538212194162580f2f50

**Comment by fzurita** [comment]
Flag value of 1 is SI_STATUS_DMA_BUSY

process_pif_ram is only called when SI_STATUS_DMA_BUSY is set in si->regs[SI_STATUS_REG]

**Comment by loganmc10** [comment]
I'm not sure that it's related to that. I reverted my DelaySI changed (so the value of SI_STATUS_DMA_BUSY shouldn't affect whether process_pif_ram is called) (https://github.com/mupen64plus/mupen64plus-core/commit/0bcfd3cc780d56c9dab8d4e837e8f2a179df6129) while keeping the PIF changes by @bsmiles32 and it's still broken.

Hopefully @bsmiles32 might have an idea, but from my testing it doesn't seem related to the DelaySI/interrupt changes from the earlier commit.

**Comment by fzurita** [comment]
I was thinking, a possible fix could just be a change of behavior. For example, if the core is commanded to load a save state before ```setup_pif_channel``` has been called, then don't load it quite yet. Wait until ```setup_pif_channel``` is called, then load it.

Now I just have to think of a non-hacky way of doing that.

**Comment by bsmiles32** [comment]
Thanks both of you for bringing this to my attention. From what I understand, the deep issue is that with this refactoring I added new state variables (eg channels[0..4].{tx,rx,tx_buf,rx_buf}) which are not saved inside the savestate, but should. Before the refactoring, these were not needed as the pif ram content was always parsed, thus avoid the need for them. But now these variables are part of the emulated system state and therefore needs to be also saved inside the savestate.

Also there might be more of these "newly created variables" that needs to be added to the savestate. As a simple rule of thumb all variables that are initialized inside poweron_XXX functions should be persisted inside the savestate. I will have to audit the whole device/ dir for such variables, so we can fix all these issues in one go and so just upgrade the savestate format once. Also in future refactoring this is likely to happen again, so I will need to be more vigilent for this kind of issues.

Hope to have some time to push a fix for that, but I can't promise it will be soon.

**Comment by loganmc10** [comment]
This is a fairly serious issue on Android, it has a "resume" option that many users use to pick up where they left off, which loads a save state like this.

Can you suggest some kind of "band-aid" fix we can apply until the save states can be looked at in more depth?

**Comment by loganmc10** [comment]
Or otherwise @fzurita could wait to update the core in mupen64plus-ae until this is fixed, or revert this PR until then as well, that might have to do

**Comment by bsmiles32** [comment]
As a band-aid, maybe adding these lines inside the savestate loading procedure could help.

```
    for(i = 0; i < PIF_CHANNELS_COUNT; ++i) {
        disable_pif_channel(&pif->channels[i]);
    }
```

This will discard any current pif channel processing, but usually games continuously poll the game controller, so a subsequent poll will re-init pif channel processings.

If this doesn't work, both reverting the PR, or not updating to latest for mupen64plus-AE are valid options.

**Comment by fzurita** [comment]
@bsmiles32 Your proposed fix means that old save states will not be compatible with the new core once the save state version is update. I guess we could use a workaround for old save states?

**Comment by bsmiles32** [comment]
Otherwise maybe forcing a process_pif_ram inside savestate loading (after having proper pif_ram content) could help reconstruct the original pif stage ?

**Comment by bsmiles32** [comment]
Or more radical, at the beginning of the savestate loading force a poweron_device ?

**Comment by fzurita** [comment]
I was thinking force a poweron_device even if a save state load command was made before ```main_run```. Once ```setup_pif_channel``` is called, then load the save state?

**Comment by fzurita** [comment]
Workaround works... But I'm seeing this:

```
09-23 00:51:09.755 18352-18400/paulscode.android.mupen64plusae.GameActivity W/Core: Unexpected command format 00 40 00 
09-23 00:51:09.765 18352-18400/paulscode.android.mupen64plusae.GameActivity W/Core: Unexpected command format 00 40 00 
```

**Comment by AmbientMalice** [comment]
I just want to note that save states being backwards compatible is extremely atypical in emulators. I appreciate why it was done, and think it greatly benefits cross-emulation testing, but it's kinda surprising there haven't been more problems cropping up. Emulators like PCSX2 and Dolphin are incompatible with older saves on a near-constant basis.

**Comment by clobber** [comment]
Higan often breaks compatibility as well, but these few emulators appear to be the exception and not the rule - I deal with and maintain two dozen core ports. Emulators should take care to not only make sure all variables are stored in the state but also to upgrade older states when a breaking change is made. Some save state consistency test code to check for missing variables, like Mednafen has just added, is a good idea to test for breakage.  My software (OpenEmu), like the Android port mentioned here, also prominently features a Virtual Console-esque pick-up-where-you-left-off "resume" function enabled by default which would be a real pain to have broken.

**Comment by Narann** [comment]
> I just want to note that save states being backwards compatible is extremely atypical in emulators.

I just pop on this to say I have a regression test system (not public yet) which highly rely on the save states. If you break save states, you break the regression test. :(

But if you "must" break savestate compatibility for a better emulator then go on, I will cry for those hundreds on save states I have T_T but that's my problem.

If there is a way to "fix old save states" (and why not even having a save state versioning) it would be seriously awesome! Same for players. Some have many save states they are preciously keeping (even if, I agree, those are tightly connected to the emulator)

**Comment by richard42** [comment]
The savestate file does have a version number in it.  Wouldn't it be possible to load these older states even with the changes to the PIF handling? They don't have the PIF internal state because the processing is done instantly -- it's either done before or after the savestate is recorded. So when loading an older savestate, couldn't you just reset these internal PIF state variables?

**Comment by bsmiles32** [comment]
Older savestates could be loaded as you suggested in a "best effort" manner either by resetting pif channels (not faithfull, but easy) or maybe re-parsing the pif ram content to properly initialize the pif channels.

On another note, I quickly checked through the device dir and there are quite a few variables which are not persisted inside the savestate :
- g_dev.ai.last_read
- g_dev.ai.delayed_carry
- g_dev.pi.cart_rom.last_write
- g_dev.pi.cart_ron.rom_written
- g_dev.dp.fb.once
- g_dev.dp.fb.infos
- g_dev.dp.fb.dirty_page
- g_dev.sp.rsp_task_locked
- g_dev.si.pif.af_rtc.control
- g_dev.si.pif.af_rtc.now
- g_dev.si.pif.af_rtc.last_update_rtc
- g_dev.si.pif.controllers.status
- g_dev.si.pif.channels.tx
- g_dev.si.pif.channels.rx
- g_dev.si.pif.channels.tx_buf
- g_dev.si.pif.channels.rx_buf
- g_dev.si.pif.controllers.tpak.enabled
- g_dev.si.pif.controllers.tpak.bank
- g_dev.si.pif.controllers.tpak.access_mode
- g_dev.si.pif.controllers.tpak.access_mode_changed
- g_dev.si.pif.controllers.tpak.cart.rom_bank
- g_dev.si.pif.controllers.tpak.cart.ram_bank
- g_dev.si.pif.controllers.tpak.cart.ram_enable
- g_dev.si.pif.controllers.tpak.cart.mbc1_mode
- g_dev.si.pif.controllers.tpak.cart.mbc3_rtc.regs
- g_dev.si.pif.controllers.tpak.cart.mbc3_rtc.latch
- g_dev.si.pif.controllers.tpak.cart.mbc3_rtc.latched_regs
- g_dev.si.pif.controllers.tpak.cart.mbc3_rtc.last_time
- g_dev.vi.count_per_scanline

And there might be more, but these are the obvious ones. And they are mostly related to recent developments (except or fb variables). I think it would help avoid this kind of error if we added for each emulated component a serialize/deserialize function (close to their poweron function) so that it is immediate if some variable is missing. But then it would likely break the current savestate format. Maybe we can do better ?

**Comment by loganmc10** [comment]
- g_dev.ai.last_read
- g_dev.ai.delayed_carry
- g_dev.dp.fb.once
- g_dev.dp.fb.infos
- g_dev.dp.fb.dirty_page
- g_dev.vi.count_per_scanline

These don't need to go into a save state, they are calculated "on the fly" each time.

I would think the cart_rom items would need to be in a save state. I've never really noticed an issue from these not being in the state, but who knows what it might be breaking.

rsp_task_locked probably also needs to go into a save state. Save states rarely work in World Driver Championship and this is probably why

**Comment by Narann** [comment]
Is this the same as https://github.com/mupen64plus/mupen64plus-ui-console/issues/38 ?

**Comment by fzurita** [comment]
Fixed with https://github.com/mupen64plus/mupen64plus-core/pull/406
