### ISSUE TITLE
Can't change pak type after game has started using CONTROL.plugin API

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#445]
The old API to change the pak type doesn't seem to work. It seems to be getting stuck in rumble pak mode. One example is Diddy kong racing.

**Comment by fzurita** [comment]
Ok, I think I see what it's happening. It's only allowing pak types that are in the mupen64plus.ini?

**Comment by bsmiles32** [comment]
Yep ! Pak switching is only between compatible paks. If there is a deeper issue let me know because I only tested this pak switching with mupen64plus-input-sdl and raphnet. The core only uses the Controls[i].Plugin at startup, then switch between compatible paks when the PAK_SWITCHING_BUTTON (0x4000) is pressed.

**Comment by fzurita** [comment]
Yeah, I'm seeing that now. The old API allowed switching paks by using ```CONTROL``` plugin field. We only seem to read that at startup.

**Comment by bsmiles32** [comment]
> If a non compatible Pak is selected, should the core use "none" instead?
Currently, I don't know what the result of that (because I hadn't considered this case when implementing this).
I think we have 2 options there :
- like you said, as the plugin is not compatible, the core ignore that and switch to none (or the first compatible pak) with a warning.
- or "trust" the user, and add, for this run, the selected pak to the list of compatible paks and proceed as normal.

**Comment by fzurita** [comment]
Any reason to not always load all pak types for all games? In a real system, there was nothing preventing someone from plugging in a rumble pak into any game.

**Comment by bsmiles32** [comment]
Only switching between compatible paks reduces the number of presses the user has to do for selecting the right pak. Especially convenient for games that are compatible with only 1 pak. And you don't gain anything by inserting a non compatible pak.

At least that was the idea.

**Comment by fzurita** [comment]
Yeah, I get it. Unfortunately, that is forcing frontends to use a key to switch Pak type. Not all devices have keys though, for example, touchscreen Android phones.

In Android, we are depending on a user to enter a menu while in game and select a Pak type using touch. We then update the ```CONTROL.plugin``` value to the user selected one.

**Comment by fzurita** [comment]
I created this pull request: https://github.com/mupen64plus/mupen64plus-core/pull/449

**Comment by fzurita** [comment]
@bsmiles32 your update to my fix almost works. In smash brothers, if the controller Pak selected at startup is the memory Pak, the core courses the rumble Pak instead of none.
