### ISSUE TITLE
Indiana Jones have bugs in dynarec

### ISSUE THREAD

**Issue by olivieryuyu** [mupen64plus/mupen64plus-core#542]
Interpreter works but dynarec has issues in game.

**Comment by loganmc10** [comment]
Can you be more specific?

**Comment by olivieryuyu** [comment]
sure

here in dynarec

![dynarec](https://user-images.githubusercontent.com/8987490/36632409-99a30688-1986-11e8-96c4-937cc1fad2e3.jpg)

and interpreter

![interpreter](https://user-images.githubusercontent.com/8987490/36632414-a1ad0a36-1986-11e8-9d4a-9f23d7fd2576.jpg)

I have a lot of little bugs in dynarec everywhere like this.

**Comment by loganmc10** [comment]
And just to be sure, this is the x64 dynarec on a PC?

**Comment by olivieryuyu** [comment]
32 bits

**Comment by loganmc10** [comment]
The waterfall looks fine with the x64 dynarec. I'll have to test the 32bit dynarec in a couple days when I'm in front of my other computer.

Is that screenshot with the HLE implementation you are working on? Or is it in LLE?

Also, do you know if the 32-bit dynarec you are using is the "new dynarec"? (where did you get mupen64plus from?) Sorry for all the questions I just want to narrow it down so I can reproduce it.

**Comment by olivieryuyu** [comment]
https://m64p.github.io 

I am using HLE on the screenshot.

It is the same in LLE, if not even worst.

**Comment by olivieryuyu** [comment]
just tested the 64bits version: no bug is it an issue with the 32 bits version.

**Comment by loganmc10** [comment]
Defining ```INTERPRET_DSLLV``` fixes the issue. So the instruction we have an issue with is DSLLV. Unfortunately I don't really know anything about dynarecs/assembly but hopefully somebody with more knowledge will be able to look at it

**Comment by Gillou68310** [comment]
I'm not familiar with the old dynarec but if I should make a guess I would say that the case ```(rd1 == ECX || rd2 == ECX)``` is probably the problem here.

This case deals with the fact that the source register is also the destination register (```DSLLV r1, r2, r1```)
```rd2 == ECX``` is probably not possible BTW.

The ```force_32``` function looks suspicious because rd is a 64bits register, the low 32bits part being allocated to ECX

**Comment by richard42** [comment]
Good diagnostic work. This code has changed a lot since I last looked at it. I suspect the force_32() is there because the author was concerned that he would run out of x86 registers. But actually this isn't a problem in this case because rs and rd are the same and thus mapped to the same x86 registers, with ECX holding the low 32 bits. However by evicting the high 32 bits from the register cache here, it will lose the high 32 bits of the result (in rd2). I would recommend just removing the force_32() function call and see if that fixes it. If so, we may need to also remove this in the other 64-bit shift instructions.
