### ISSUE TITLE
Unable to enter and edit config

### ISSUE THREAD

**Issue by Builderofawsome** [mupen64plus/mupen64plus-core#567]
So I was trying to edit the config so I could change the controls of Mupen64, but every time I entered `~/.config/mupen64plus/mupen64plus.cfg ` into the code, this got spat out
`Thibautss-MacBook-Air:mupen64plus-bundle-osx64-2 Thibaut$ ~/.config/mupen64plus/mupen64plus.cfg
-bash: /Users/Thibaut/.config/mupen64plus/mupen64plus.cfg: Permission denied`
Anyone know how to fix this?

**Comment by richard42** [comment]
this config file is just a file, by entering just its name on the command prompt, you are trying to execute it like a program. It says 'permission denied' because it's not executable. You need to edit this file to make changes. I think from the Finder you can type Command-Shift-G to bring up a dialog that lets you type in the directory to view. Type `~/.config/mupen64plus/` to open a Finder window at this location, and then open the `mupen64plus.cfg` file with a text editor.

**Comment by Builderofawsome** [comment]
Thanks, I figured out how to do it because of this. Thanks man.
