### ISSUE TITLE
Following osx_build_instructions.txt: boost/filesystem.hpp not found when installing glide

### ISSUE THREAD

**Issue by mitchlloyd** [mupen64plus/mupen64plus-core#60]
Following the installation instructions found here

https://github.com/mupen64plus/mupen64plus-core/blob/master/tools/osx_build_instructions.txt

I got this error when I installed:

```
../../src/GlideHQ/TxHiResCache.h:37:10: fatal error: 'boost/filesystem.hpp' file not found
#include <boost/filesystem.hpp>
         ^
1 error generated.
make: *** [_obj/GlideHQ/TxFilterExport.o] Error 1
```

I'm not sure why this boost library can't be found. First I installed boost with `brew install boost` which installed version 1.57.0. After that I tried installing boost manually by following the instructions on [boost.org](http://www.boost.org/doc/libs/1_57_0/more/getting_started/unix-variants.html). I when installing manually I installed without the `--with-libraries` option, so I believe all of the libraries, including filesystem have been installed.

Is there more information that could be provided in the `osx_build_instructions.txt` that could help with the configuration problem I'm having?

**Comment by richard42** [comment]
Hi Mitch.  Where did Boost get installed on your system?  I installed it through Mac Ports, and it must have installed to some system location (probably /opt/local) which got specified to the compiler via an '-I' flag.  This may be a shortcoming in the makefile; because it should be giving a compiler option to specify the include and library paths for Boost.  If you build with "./m64p_build.sh V=1" (or "make V=1" directly from the mupen64plus-video-glide64mk2/projects/unix folder) then it should print out the full compiler commands, which will also be helpful for debugging this.

**Comment by twinaphex** [comment]
As a long-term goal, can we try refactoring the code in GlideHQ so that it's no longer reliant on Boost?

Getting rid of this dependency would be a huge win for my fork too as I refuse to require such a big dependency, so right now I just stub out the GlideHQ parts altogether.

If nobody else wants to make some efforts towards doing this I will take up the initiative myself.

**Comment by littleguy77** [comment]
> so right now I just stub out the GlideHQ parts altogether.

Same on mupen64plus-ae.  I can take a peek at this if I manage to find some time.

**Comment by Narann** [comment]
From my perspective, there is nobody in upstream involved in GlideHQ dev so if every downstream devs (retro arch + AE) are ready to collaborate to decrease upstream dependencies that would be great! (Yeah, boost is a big dependency).

I've [created a ticket](https://github.com/mupen64plus/mupen64plus-video-glide64mk2/issues/46) to track this. I encourage you to discuss to ensure the work will benefit as much downstream project as possible! :)

**Comment by qbwaggle** [comment]
The problem is in the makefile for glide64mk2 plugin.

Edit ../mupen64plus-core-master/source/mupen64plus-video-glide64mk2/projects/unix/Makefile

Go to "set special flags per-system" section and add your boost directory under the OS X 64BITS (assuming you're running 10.6+).

For me I added the following:
```
-I /usr/local/Cellar/boost/1.56.0/include
```
to the following as shown:
```
ifeq ($(OS), OSX)
  #xcode-select has been around since XCode 3.0, i.e. OS X 10.5
  OSX_SDK_ROOT = $(shell xcode-select -print-path)/Platforms/MacOSX.platform/Developer/SDKs
  OSX_SDK_PATH = $(OSX_SDK_ROOT)/$(shell ls $(OSX_SDK_ROOT) | tail -1)

  ifeq ($(CPU), X86)
    LDFLAGS += -bundle -L/opt/local/lib
    CXXFLAGS += -stdlib=libc++
    LDLIBS += -ldl
    ifeq ($(ARCH_DETECTED), 64BITS)
      CFLAGS += -pipe -I /opt/local/include -I /usr/local/Cellar/boost/1.56.0/include -arch x86_64 -mmacosx-version-min=10.7 -isysroot $(OSX_SDK_PATH)
    else
      CFLAGS += -pipe -I /opt/local/include -mmmx -msse -fomit-frame-pointer -arch i686 -mmacosx-version-min=10.7 -isysroot $(OSX_SDK_PATH)
    endif
  endif
endif
```

**Comment by mitchlloyd** [comment]
Modifying the makefile as suggested by @qbwaggle did work for me (using boost 1.57.0 in my case).

One option for the documentation would be to include information for homebrew users telling them to use:

```
brew install boost
brew link boost
```

Which will put symlinks in `/usr/local/include` (this is also the path used by default if you install boost from source on a Mac without homebrew). Then you should be able to add `-I /usr/local/include` to the makefile. At least this way the version of Boost would not be hardcoded in the Makefile.

Thanks for the help!
