### ISSUE TITLE
Command and conquer in-game save corruption

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#600]
It seems that Mupen64plus is unable to create in-game saves for command and conquer. Whenever this is attempted, the following error occurs within the game:

![command conquer-000](https://user-images.githubusercontent.com/11581687/50637542-6048c100-0f28-11e9-85ef-4dfcc2ff842f.png)

This may just be a game database issue. The wrong save type may be specified.

**Comment by fzurita** [comment]
Save type doesn't seem to match the project 64 rdb, but fixing it doesn't allow the game to save.

**Comment by loganmc10** [comment]
I spent some time looking into this. At least now, mupen64plus and PJ64 save game formats match (flash ram), maybe the .ini has been updated since this report.

It still doesn't work, it does work in PJ64. Theoretically should be easy enough to fix? Just need to compare the implementation in PJ64 to mupen64plus, there are definite differences

**Comment by fzurita** [comment]
This is probably fixed.
