### ISSUE TITLE
Jet force gimini (U) locks up

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-core#610]
Jet Force Gemini crashes with a black screen after exiting the last section or entering the goal door in Interior Goldwood.

This happen with the new dynarec or interpreter. Also with LLE or HLE plugins. This feels a lot like the freezes in perfect dark at the end of a level, so some sort of timing issue. 

Here is a save state to reproduce, simply enter the sparkly area and push A to get past the stats.
[Jet.Force.Gemini_state.zip](https://github.com/mupen64plus/mupen64plus-core/files/2781086/Jet.Force.Gemini_state.zip)

**Comment by loganmc10** [comment]
Do you have a save game file for JFG that I could use to reproduce this? I'd like to see if https://github.com/mupen64plus/mupen64plus-core/pull/701 makes any difference, but the nature of the change makes savestates incompatible.

**Comment by fzurita** [comment]
I don't have a compatible save state unfortunately. And I got that save state from someone else.

**Comment by loganmc10** [comment]
I got savestates working with that PR, didn't fix this issue unfortunately

**Comment by loganmc10** [comment]
I debugged this a bit, commenting out this line:

https://github.com/mupen64plus/mupen64plus-core/blob/master/src/device/r4300/tlb.c#L143

Fixes the issue. It's the exact same thing that prevents Rat Attack from booting. I always thought that issue was specific to Rat Attack, but you've discovered another case. I'll continue looking into this, there must be something we are doing wrong when dealing with these TLB exceptions. I'm hoping now that I have 2 examples to work with I'll be able to crack it. I'm guessing whatever the fix is will fix both games.

**Comment by fzurita** [comment]
Great!

**Comment by loganmc10** [comment]
I'm pretty convinced that this has something to do with flashram in JFG. Right when you enter that room, the game does some reads/writes to the flashram. I assume because that is a save point.

I haven't really been able to pinpoint the issue, some stuff I read online leads me to believe that JFG used a different type of flashram chip than what was typical of other games. It's also hard to know if the data in the save state is already "corrupted beyond repair", and even if something was fixed properly, it wouldn't show up when testing that save state.

**Comment by fzurita** [comment]
Maybe it's similar issue to DK64. If one uses save states there, the save eventually gets corrupt.

**Comment by fzurita** [comment]
I have the feeling that this is probably fixed.
