### ISSUE TITLE
Uncached memory code execution support

### ISSUE THREAD

**Issue by LuigiBlood** [mupen64plus/mupen64plus-core#673]
I've been working on a project that required me to run code on uncached RAM (and yes I've tried on cached locations but there was no way for it to work on real hardware), while it works fine on emulators like Project64, mupen64plus closes immediately, thinking something must be wrong.

**Comment by LuigiBlood** [comment]
The project in question that crashes mupen64plus is this:
https://github.com/LuigiBlood/zelda_dawn_dusk/releases

You can use an original Zelda OoT ROM (any version), 64DD IPL and a disk (the issue only happens with disk version).

**Comment by loganmc10** [comment]
@LuigiBlood I was testing this out, the game seems to work:

![image](https://user-images.githubusercontent.com/848146/75115297-4382b780-561a-11ea-926e-7a224ee3efc1.png)

Tested with the Japanese version because I'm not sure where to get the American IPL ROM.

I tested with the cached interpreter, maybe this is a bug specific to the dynarec?

**Comment by loganmc10** [comment]
Nevermind I found the US IPL on your website, the US ROM appears to work as well, I'm guessing this is specific to the dynarec

**Comment by LuigiBlood** [comment]
To be honest I didn't try this with the latest source so maybe it fixed itself at some point.
