### ISSUE TITLE
Mupen32.exe, more like

### ISSUE THREAD

**Issue by demonjacobs666** [mupen64plus/mupen64plus-core#674]
So, when does the 64-bit Windows version come out?

**Comment by nlburgin** [comment]
Pretty sure the code can already be built for 64-bit windows, it's just they apparently haven't bothered setting that up in their build automation on Github yet.

I'm pretty sure BizHawk is 64-bit, and it has (a modified version of of) Mupen64Plus inside of it. However if what you're looking to gain is better performance, you probably won't find it there, since all the TAS-oriented features hooked into it tend to slow it down quite a bit.

**Comment by mackal** [comment]
There likely is little to no reason to release a 64 bit version. It's just an extra step for 0 benefit. What do you expect out of a 64-bit version?

**Comment by demonjacobs666** [comment]
does nobody else find it odd that mac and linux versions are 64-bit, but the windows version is 32-bit, despite windows itself being 64-bit?

**Comment by nlburgin** [comment]
>does nobody else find it odd that mac and linux versions are 64-bit, but the windows version is 32-bit, despite windows itself being 64-bit?

AFAIK, Mac doesn't support 32-bit at all. I don't think it ever did, because it didn't switch from 32-bit Intel to 64-bit Intel; instead it switched from _IBM POWER_ architecture to 64-bit Intel. Weird situation there.

As far as linux goes, I think using legacy 32-bit builds there is usually less convenient than it is on Windows, however on the other hand it's very easy to get a 64-bit compiler and the build system is pretty much the same either way. 

Whereas to get 64-bit on Windows, they'd have to upgrade their Windows build system to something much newer (apparently they're still on Visual Studio 2013).

>There likely is little to no reason to release a 64 bit version. It's just an extra step for 0 benefit. What do you expect out of a 64-bit version?

Technically a 64-bit version would probably have somewhat better performance, except it already runs  at full speed anyway on pretty much all 64-bit systems without bothering with that so... :man_shrugging:

**Comment by StenApp** [comment]
OSX 10.4 was 32 Bit and supported 64 bit Applications!  It had a mechanism to seitch between those two modes

**Comment by nlburgin** [comment]
>OSX 10.4 was 32 Bit and supported 64 bit Applications!

I hadn't heard of that.

I'm pretty sure that to support both modes, the OS kernel has to running in 64-bit, but I believe it *is* possible to use 32-bit pointers even when running the 64-bit instruction set. 

In fact I think Linux actually did experiment with this in the form of the [x32 ABI](https://en.wikipedia.org/wiki/X32_ABI), but it never really caught on. I had no idea Mac was actually using something like that in production for a while.

**Comment by DaveGravel** [comment]
You can try this, It is my personal build 64bits version for win10.
https://www.mediafire.com/file/zzn7v66wni0g0dc/oxMupen64Plus_64bits_alpha_0_3.zip

**Comment by richard42** [comment]
64-bit Windows builds can be made with MXE or Cygwin or something like that. We only publish 32-bit Windows builds because they are compiled with Visual Studio, and historically Visual Studio treated all integers declared as "long" as being 32-bits which was pretty stupid and incompatible with making a working 64-bit build from our source code. This could be fixed by just re-writing all of the offending integer types with stdint.h names, which any enterprising Windows developer is welcome to do.
