### ISSUE TITLE
Missing "mupen64plus.dll" when compiling on windows

### ISSUE THREAD

**Issue by OEMSg** [mupen64plus/mupen64plus-core#749]
I'm trying to compile on Windows using the guide from the Wiki (https://mupen64plus.org/wiki/index.php?title=CompilingOnWindows) and VisualStudio2019, everything goes well except for that module which isn't generating at all

**Comment by Jj0YzL5nvJ** [comment]
This is a [much better guide](https://github.com/mupen64plus/mupen64plus-ui-console/commit/0a15c7dda5c25653ca66812e65d9d227b5f56252) if you understand batch.

What happens if you compile _mupen64plus-core.vcxproj_ individually?
[Look at this log as an example...](https://ci.appveyor.com/project/Narann/mupen64plus-core/builds/31961497/job/xtrg6yk7d6icayrd)

**Comment by OEMSg** [comment]
It worked!! I just needed to use the native tools from the command promt of visual studio and compile directly from the ui-console solution, thank you, made my day :D
