### ISSUE TITLE
2.5.9 Linux 64 binary bundle - Illegal instruction

### ISSUE THREAD

**Issue by majorendian** [mupen64plus/mupen64plus-core#902]
When downloading the 2.5.9 release binary bundle and running the binary I get "illegal instruction" error.
When looking at the assembly via objdump -d mupen64plus I noticed a HTL instruction right at main.
Is this intentional? Or did I look at the wrong function.
gdb output:
```
root@slax:~/roms/mupen64plus-bundle-linux64-2.5.9# gdb ./mupen64plus
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./mupen64plus...(no debugging symbols found)...done.
(gdb) r
Starting program: /root/roms/mupen64plus-bundle-linux64-2.5.9/mupen64plus 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000000000403590 in ?? ()
(gdb) 
```
System:
```
$> uname -a
Linux slax 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux
```
CPU: Core2Quad

**Comment by Jj0YzL5nvJ** [comment]
Dynamic linker issue #892

<details>
  <summary>More...</summary>

#641
#754
#780
#797
#822

</details>

If you can, use [m64p](https://github.com/loganmc10/m64p/releases) instead.

**Comment by richard42** [comment]
It's not the HALT instruction; if you look at the address given by GDB, this is the assembly code:
  403590:       c5 f8 ae 5c 24 fc       vstmxcsr -0x4(%rsp)
It's an AVX instruction, which is not available on your core2quad. I'm not sure exactly how that got in there but apparently that's what GCC emitted when I made the 2.5.9 build. I bet our makefile has something like -march=auto and the CPU on this machine is an i7 with AVX. I'll make a note to change the compiler flags when making new builds in the future so that they don't include unsupported instructions like this.

To get around this problem, you could build from source on your machine or use the pre-built m64p binaries like Jj0YzL5nvJ suggested.

**Comment by majorendian** [comment]
Thanks, I compiled it from source yes. And yes I know it was that strange instruction I just didnt update my report properly.
I just wanted to report this issue since you asked for bug reports and this was very strange in terms of a release.
Compiling from source fixed the issue. I needed it anyway to enable the Debugger since I had an issue with that as well.
Thank you for resolving this issue so quickly.
